const themeToggle=document.getElementById('themeToggle');const body=document.body;const html=document.documentElement;const sunIcon=document.querySelector('.sun-icon');const moonIcon=document.querySelector('.moon-icon');const savedTheme=localStorage.getItem('theme')||'dark';body.classList.remove('dark-mode','light-mode');body.classList.add(savedTheme+'-mode');html.classList.remove('dark-mode','light-mode');html.classList.add(savedTheme+'-mode');updateThemeIcon(savedTheme);function updateThemeIcon(theme){if(theme==='dark'){sunIcon.style.display='block';moonIcon.style.display='none'}else{sunIcon.style.display='none';moonIcon.style.display='block'}}
themeToggle.addEventListener('click',()=>{const isDark=body.classList.contains('dark-mode');const newTheme=isDark?'light':'dark';body.classList.remove('dark-mode','light-mode');body.classList.add(newTheme+'-mode');html.classList.remove('dark-mode','light-mode');html.classList.add(newTheme+'-mode');localStorage.setItem('theme',newTheme);updateThemeIcon(newTheme)});const navbar=document.getElementById('navbar');window.addEventListener('scroll',()=>{if(window.scrollY>50){navbar.classList.add('scrolled')}else{navbar.classList.remove('scrolled')}});document.querySelectorAll('a[href^="#"]').forEach(anchor=>{anchor.addEventListener('click',function(e){e.preventDefault();const target=document.querySelector(this.getAttribute('href'));if(target){target.scrollIntoView({behavior:'smooth',block:'start'})}})});const canvas=document.getElementById('heroCanvas');const ctx=canvas.getContext('2d');function resizeCanvas(){canvas.width=canvas.offsetWidth;canvas.height=canvas.offsetHeight}
resizeCanvas();window.addEventListener('resize',resizeCanvas);const particles=[];const particleCount=50;class Particle{constructor(){this.x=Math.random()*canvas.width;this.y=Math.random()*canvas.height;this.vx=(Math.random()-0.5)*0.5;this.vy=(Math.random()-0.5)*0.5;this.radius=Math.random()*2+1}
update(){this.x+=this.vx;this.y+=this.vy;if(this.x<0||this.x>canvas.width)this.vx*=-1;if(this.y<0||this.y>canvas.height)this.vy*=-1}
draw(){ctx.beginPath();ctx.arc(this.x,this.y,this.radius,0,Math.PI*2);ctx.fillStyle='rgba(14, 165, 233, 0.5)';ctx.fill()}}
for(let i=0;i<particleCount;i++){particles.push(new Particle())}
function animate(){ctx.clearRect(0,0,canvas.width,canvas.height);particles.forEach(particle=>{particle.update();particle.draw()});particles.forEach((p1,i)=>{particles.slice(i+1).forEach(p2=>{const dx=p1.x-p2.x;const dy=p1.y-p2.y;const distance=Math.sqrt(dx*dx+dy*dy);if(distance<100){ctx.beginPath();ctx.strokeStyle=`rgba(14, 165, 233, ${0.2 * (1 - distance / 100)})`;ctx.lineWidth=1;ctx.moveTo(p1.x,p1.y);ctx.lineTo(p2.x,p2.y);ctx.stroke()}})});requestAnimationFrame(animate)}
animate();const contactForm=document.getElementById('contactForm');const formMessage=document.getElementById('formMessage');contactForm.addEventListener('submit',async(e)=>{e.preventDefault();const formData=new FormData(contactForm);try{const response=await fetch(contactForm.action,{method:'POST',body:formData,headers:{'Accept':'application/json'}});if(response.ok){contactForm.reset();formMessage.textContent="Thank you! Your message has been sent.";formMessage.style.color='green';formMessage.classList.add('show');setTimeout(()=>{formMessage.classList.remove('show')},5000)}else{formMessage.textContent="Oops! Something went wrong.";formMessage.style.color='red';formMessage.classList.add('show');setTimeout(()=>{formMessage.classList.remove('show')},5000)}}catch(error){formMessage.textContent="Network error. Please try again later.";formMessage.style.color='red';formMessage.classList.add('show');setTimeout(()=>{formMessage.classList.remove('show')},5000)}});const mobileToggle=document.getElementById('mobileToggle');const navLinks=document.querySelector('.nav-links');mobileToggle.addEventListener('click',()=>{navLinks.style.display=navLinks.style.display==='flex'?'none':'flex'});const filterButtons=document.querySelectorAll('.filter-btn');const projectCards=document.querySelectorAll('.project-card');let initialize_category=document.querySelector('[data-filter="web"]');console.log(initialize_category)
filterButtons.forEach(button=>{button.addEventListener('click',()=>{filterButtons.forEach(btn=>btn.classList.remove('active'));button.classList.add('active');const filter=button.dataset.filter;console.log(filter)
projectCards.forEach(card=>{if(card.dataset.category===filter){card.style.display='block'}else{card.style.display='none'}})})})
initialize_category.click()